# Generated by Django 4.0.3 on 2022-06-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tg',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
